### PR TITLE
Get phenotype statistics

### PR DESCRIPTION
**Pull request by ewartj**
## Overview and purpose

Adds a function to get a table of statistics on a phenotype in `cloudos/cohorts/cohort.py`.

+ Adds `get_phenotype_statistics()` method to get statistics on a phenotype of interest.
+ Adds `__fetch_stats_table()` method to requests information on a phenotype.

## How to test
Install from Github. Python >= 3.8 and pip are required.
Clone the repo and install it using pip:

```
git clone https://github.com/lifebit-ai/cloudos-py
cd cloudos-py
git checkout get_phenotype_statistics
pip install -r requirements.txt
pip install -e .
```

#### Testing

```python
>>> from cloudos.cohorts import Cohort, CohortBrowser
>>> apikey = "***"
>>> workspace_id = "5f7c8696d6ea46288645a89f"
>>> cloudos_url = "http://cohort-browser-dev-110043291.eu-west-1.elb.amazonaws.com"
```

Get information on a phenotype of type bars:

```python
>>> cb = CohortBrowser(apikey, cloudos_url, workspace_id)
>>> c = cb.load_cohort("61cbd1c5b948af25c65ef7d0")
>>> df = c.get_phenotype_statistics(pheno_id = 4)
>>> print(df)
               value  count
0             Female     16
1               Male     22
2  Prefer not to say     11
3             Cancer   8674
4               male      1
5      Rare Diseases  35993
>>> print(df.shape)
(6, 2)
>>> print(df.info())
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   value   6 non-null      object
 1   count   6 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 224.0+ bytes
None
```

Get information on a phenotype of type histogram:

```python
>>> df = c.get_phenotype_statistics(pheno_id = 99)
>>> print(df)
      value  count
0        12      1
1     35.94      4
2     35.93      3
3      35.9      1
4     35.88      1
...     ...    ...
1275  53.47      2
1276  53.17      1
1277  53.51      1
1278  53.19      1
1279  53.42      1

[1280 rows x 2 columns]
>>> print(df.shape)
(1280, 2)
>>> print(df.info())
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   value   1280 non-null   object
 1   count   1280 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 20.1+ KB
None
```

Get information on a phenotype of type text_search:

```python
>>> df = c.get_phenotype_statistics(pheno_id = 238)
>>> print(df)
    value  count
0   R1CJ7     24
1   RYJ03     49
2   RDZ00     17
3   SSA20     26
4   RWA16      6
..    ...    ...
68    RJ1     36
69  RVJ01     29
70    REP    154
71    RX1    353
72    RW4      6

[73 rows x 2 columns]
>>> print(df.shape)
(73, 2)
>>> print(df.info())
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   value   73 non-null     object
 1   count   73 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
None
```

### CODE REVIEW

**Comment by cgpu** [comment]
@ilevantis @dapineyro @ewartj what do we need from this PR to be merged?

**Comment by dapineyro** [comment]
@ewartj I reviewed the code and looks great! :+1: However, the test commands do not work on my end. I know that these cohorts in test environments can be removed and the PR is quite old. Could you confirm that the test is still working on your end? If so, could you send me the appropriate credentials via slack?

**Review by dapineyro — APPROVED** [review]
LGTM!

**Review by ilevantis — APPROVED** [review]
LGTM 👍 !

**Pull request merged**
